### ISSUE TITLE
Allow for custom duration without specifying custom easing

### ISSUE THREAD

**Issue by andrewrubin** [wethegit/wtc-tween#1]
## Description
If there's no `timingFunction` specified in the options object, it breaks.
Would be good to allow for something like this:
```js
tween(0, 1, value =>{
  // …code
},
{
  duration: 2000
});
```

**Comment by marlonmarcello** [comment]
Commit https://github.com/wethegit/wtc-tween/commit/91b4d16a1474d7ebfb09ae8625ac2cd2f555e391 should fix this.
Gonna publish a patch version.

**Comment by marlonmarcello** [comment]
Done. https://github.com/wethegit/wtc-tween/commit/88b8347cb85e1863831803931299226edbd8b772
Version `1.0.7` is up
